# 全局配置

# 系统配置
system:
    # 环境变量
    env: 'dev'
    # socket端口
    socket-port: 8866
    # websocket端口
    websocket-port: 7777

# redis配置
redis:
    # 主机地址
    host: '127.0.0.1'
    # 端口
    port: 6379
    # 密码
    password: ''
    # 数据库实例
    database: 10
    # 连接超时时长
    timeout: 2000

# 日志配置
log:
    # 日志文件路径
    log-path: './logs/'
    # 是否输出日志文件
    log-file: 'cmdmgt'
    # 日志级别
    level: 'info'

